"""add assigned_to and resolution to tickets

Revision ID: e9906b88e6c6
Revises: 2049724c2619
Create Date: 2026-05-19 16:57:24.927228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9906b88e6c6'
down_revision: Union[str, Sequence[str], None] = '2049724c2619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.add_column('tickets', sa.Column('resolution', sa.String(), nullable=True))
    op.create_foreign_key(None, 'tickets', 'users', ['assigned_to'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tickets', type_='foreignkey')
    op.drop_column('tickets', 'resolution')
    op.drop_column('tickets', 'assigned_to')
    # ### end Alembic commands ###
